### PR TITLE
Allows for configurable tmp_dir in DwCArchiveReader

### PR DESCRIPTION
**Pull request by evindunn**

### CODE REVIEW

**Comment by evindunn** [comment]
Hi all,

I kept running out of space in the default temp directory when reading from a big archive, so I wrote in a little utility for setting the temp directory when creating the DwCArchiveReader. Also included a test method for the utility.

Thanks!

**Comment by niconoe** [comment]
Thanks a lot for your contribution, that's great!

**Comment by niconoe** [comment]
... And thanks for your patience!

**Comment by niconoe** [comment]
@evindunn : a new version (0.14.0) that includes your contribution has been issued!

**Comment by evindunn** [comment]
Thanks @niconoe !

**Pull request merged**
